apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: syfo-narmesteleder-leesah
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
    maxCompactionLagMs: 3e+9 # ~ 35 days
    minCompactionLagMs: 2.7e+9 # ~ 31 days
  acl:
    - team: team-esyfo
      application: dinesykmeldte-backend
      access: read
    - team: team-esyfo
      application: esyfo-narmesteleder
      access: readwrite
