apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: esyfo-narmesteleder
  namespace: team-esyfo
  annotations:
    texas.nais.io/enabled: "true"
spec:
  ingresses:
    - https://narmesteleder-api.intern.nav.no
    - https://narmesteleder-api.nav.no/api/v1/linemanager
    - https://narmesteleder-api.nav.no/swagger
    - https://narmesteleder-api.nav.no/openapi
  image: {{image}} #
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  startup:
    path: /internal/is_alive
    initialDelay: 10
    periodSeconds: 10
    timeout: 5
    failureThreshold: 720
  replicas:
    max: 4
    min: 2
    cpuThresholdPercentage: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 768Mi
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-1-5120
        name: esyfo-narmesteleder-instance
        collation: nb_NO.UTF8
        databases:
          - name: esyfo-narmesteleder-db
            envVarPrefix: NARMESTELEDER_DB
        diskAutoresize: true
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          delegationSource: altinn
          enabled: true
          product: syfo
          separator: "/"
          name: narmesteleder/lps
          atMaxAge: 680
      consumes:
        - name: "digdir:dialogporten.serviceprovider"
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: narmesteleder-frontend
        - application: dinesykmeldte-backend
        - application: min-side-arbeidsgiver
          namespace: fager
        - application: syfo-budstikka
          namespace: team-esyfo
        - application: syfo-oppfolgingsplan-backend
        - application: ditt-sykefravaer
          namespace: flex
    outbound:
      rules:
        - application: dinesykmeldte-backend
        - application: arbeidsgiver-altinn-tilganger
          namespace: fager
      external:
        - host: aareg-services.prod-fss-pub.nais.io
        - host: ereg-services.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: platform.altinn.no
  kafka:
    pool: nav-prod
  valkey:
    - instance: felles-cache
      access: readwrite
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:MaxRAMPercentage=50 -Dlogback.configurationFile=logback.xml
    - name: AZURE_APP_PRE_AUTHORIZED_APPS
      value: '[{"name":"syfo-budstikka","clientId":"6579b386-43ea-4089-9244-5ac2b1f81c71"},{"name":"syfo-oppfolginsplan-backend","clientId":"2dc3ddfa-0a3d-4a8b-9a8f-1f2b543830f6"}]'
    - name: PDL_BASE_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: prod-fss.pdl.pdl-api
    - name: AAREG_BASE_URL
      value: https://aareg-services.prod-fss-pub.nais.io
    - name: AAREG_SCOPE
      value: prod-fss.arbeidsforhold.aareg-services-nais
    - name: DIALOGPORTEN_SCOPE
      value: digdir:dialogporten.serviceprovider
    - name: ALTINN_3_BASE_URL
      value: https://platform.altinn.no
    - name: DINESYMELDTE_BASEURL
      value: http://dinesykmeldte-backend
    - name: DINESYMELDTE_SCOPE
      value: prod-gcp.team-esyfo.dinesykmeldte-backend
    - name: EREG_BASE_URL
      value: https://ereg-services.prod-fss-pub.nais.io
    - name: ALTINN_TILGANGER_BASE_URL
      value: http://arbeidsgiver-altinn-tilganger.fager
    - name: FRONTEND_BASE_URL
      value: https://www.nav.no/arbeidsgiver
    - name: PUBLIC_INGRESS_URL
      value: https://narmesteleder-api.nav.no
    - name: PERSIST_LEESAH_NL_BEHOV
      value: "true"
    - name: CONSUME_KAFKA_TOPICS
      value: "true"
    - name: DIALOGPORTEN_TASK_ENABLED
      value: "true"
    - name: DIALOGPORTEN_UPDATE_POLLING_DELAY
      value: "10m"
    - name: PERSIST_SENDT_SYKMELDING
      value: "true"
    - name: MAINTENANCE_TASK_DELAY
      value: "1h"
    - name: DAYS_AFTER_TOM_TO_EXPIRE_BEHOVS
      value: "16"
    - name: BEHOV_MAINTENANCE_TASK_ENABLED
      value: "true"
    - name: PERSIST_NARMESTELEDER_REGISTER
      value: "true"
    - name: PDL_LEESAH_CONSUMER_ENABLED
      value: "true"
    - name: PERSON_ENRICHMENT_TASK_ENABLED
      value: "true"
  envFrom:
    - secret: altinn-subscription-key
